//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikeSelector.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HikeSelector.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoRoutes {
            get {
                return ResourceManager.GetString("NoRoutes", resourceCulture);
            }
        }
        
        internal static string SuggestRoute {
            get {
                return ResourceManager.GetString("SuggestRoute", resourceCulture);
            }
        }
        
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        internal static string TTRNone {
            get {
                return ResourceManager.GetString("TTRNone", resourceCulture);
            }
        }
        
        internal static string TTRShort {
            get {
                return ResourceManager.GetString("TTRShort", resourceCulture);
            }
        }
        
        internal static string TTRDayTrip {
            get {
                return ResourceManager.GetString("TTRDayTrip", resourceCulture);
            }
        }
        
        internal static string TTROverNight {
            get {
                return ResourceManager.GetString("TTROverNight", resourceCulture);
            }
        }
        
        internal static string TimeToTravel {
            get {
                return ResourceManager.GetString("TimeToTravel", resourceCulture);
            }
        }
        
        internal static string RouteLenghtShort {
            get {
                return ResourceManager.GetString("RouteLenghtShort", resourceCulture);
            }
        }
        
        internal static string RouteLenghtMedium {
            get {
                return ResourceManager.GetString("RouteLenghtMedium", resourceCulture);
            }
        }
        
        internal static string RouteLengthLong {
            get {
                return ResourceManager.GetString("RouteLengthLong", resourceCulture);
            }
        }
        
        internal static string RouteLength {
            get {
                return ResourceManager.GetString("RouteLength", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string RouteEdit {
            get {
                return ResourceManager.GetString("RouteEdit", resourceCulture);
            }
        }
        
        internal static string RouteCreate {
            get {
                return ResourceManager.GetString("RouteCreate", resourceCulture);
            }
        }
    }
}
